### ISSUE TITLE
Getting killed :( uwu

### ISSUE THREAD

**Issue by jhKessler** [lennybakkalian/Web3Manager#1]
Can I run it on Mac?

**Comment by jhKessler** [comment]
![image](https://user-images.githubusercontent.com/68814636/169547270-5a36072c-6b81-4528-ba79-d961fd4634db.png)

**Comment by lennybakkalian** [comment]
Hey,
I would suggest using the CELEB-A Dataset.
As for the lr, yes its probably too high, but feel free to try different values for yourself and see what works best for you.
Also: Resolution 4096? If you dont have an NVIDIA Server Farm I don't think thats possible

**Comment by jhKessler** [comment]
Can you fix my printer?

**Comment by lennybakkalian** [comment]
Johnny makes fun of you. @rushic24

**Comment by lennybakkalian** [comment]
On github you can click on "edited" to see the real previous message.

**Comment by lennybakkalian** [comment]
![image](https://user-images.githubusercontent.com/26249979/169557613-c11b9bed-b996-4e23-ad48-f2ef8ada2fa2.png)

**Comment by lennybakkalian** [comment]
Besides, johnny is someone who doesn't gank teemo top's. So you see what kind of subhuman you had to deal with.

**Comment by jhKessler** [comment]
I don't even know you wtf

**Comment by lennybakkalian** [comment]
i will close this issue and not help johnny unless i get top gank.
